site_name: "BioV"
site_url: https://tcztzy.github.io/biov/
repo_url: https://github.com/tcztzy/biov

theme:
  name: material
  features:
    - navigation.indexes
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
          show_root_heading: false

markdown_extensions:
- admonition
- pymdownx.superfences
- attr_list

nav:
- Home: index.md
- Guides:
  - Configuration: guides/configuration.md
- API Reference: reference/
