[project]
name = "biov"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tang Ziya", email = "tcztzy@gmail.Com" }
]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/biov"]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
venvPath = "."
venv = ".venv"
