"""Full-output scientific and boundary checks for the first native sequence slice.

Provenance: INSDC Feature Table 11.4 (April 2026), sections 7.4.1 and 7.4.3,
https://www.insdc.org/submitting-standards/feature-table/ . The independent
set-based oracle below does not import BioV or Biopython complement tables.
Biopython 1.88 is the separately versioned differential reference in uv.lock.
See docs/guides/sequence-contract.md for the accepted contract and limitations.
"""

import importlib
import random
from collections.abc import Callable
from importlib.machinery import EXTENSION_SUFFIXES
from itertools import product
from pathlib import Path

import Bio
import pandas as pd
import pytest
from Bio.Seq import Seq as ReferenceSeq

import biov

REFERENCE_BIOPYTHON_VERSION = "1.88"
DNA_ALPHABET = "ACGTRYSWKMBDHVN"
RNA_ALPHABET = "ACGURYSWKMBDHVN"
PROTEIN_ALPHABET = "ACDEFGHIKLMNPQRSTVWYBJOUXZ*"
OPERATIONS = ("normalize_sequences", "reverse_complements")

# Biological set meanings transcribed from INSDC 11.4 section 7.4.1.
# Sets plus canonical-base pairing provide a structurally independent oracle.
_DNA_BASE_SETS = {
    "A": frozenset("A"),
    "C": frozenset("C"),
    "G": frozenset("G"),
    "T": frozenset("T"),
    "R": frozenset("AG"),
    "Y": frozenset("CT"),
    "S": frozenset("CG"),
    "W": frozenset("AT"),
    "K": frozenset("GT"),
    "M": frozenset("AC"),
    "B": frozenset("CGT"),
    "D": frozenset("AGT"),
    "H": frozenset("ACT"),
    "V": frozenset("ACG"),
    "N": frozenset("ACGT"),
}

# Hand-derived one-symbol fixtures, not generated by the new implementation.
_DNA_SYMBOL_COMPLEMENTS = (
    ("A", "T"),
    ("C", "G"),
    ("G", "C"),
    ("T", "A"),
    ("R", "Y"),
    ("Y", "R"),
    ("S", "S"),
    ("W", "W"),
    ("K", "M"),
    ("M", "K"),
    ("B", "V"),
    ("D", "H"),
    ("H", "D"),
    ("V", "B"),
    ("N", "N"),
)


def _set_oracle(value: str, kind: str) -> str:
    """Derive each ambiguous complement from canonical nucleotide sets.

    Returns:
        Complete reverse complement encoded with the declared IUPAC alphabet.
    """
    base_sets = _DNA_BASE_SETS
    pairing = {"A": "T", "T": "A", "C": "G", "G": "C"}
    if kind == "rna":
        base_sets = {
            symbol.replace("T", "U"): frozenset(
                base.replace("T", "U") for base in bases
            )
            for symbol, bases in _DNA_BASE_SETS.items()
        }
        pairing = {"A": "U", "U": "A", "C": "G", "G": "C"}
    symbol_for_set = {bases: symbol for symbol, bases in base_sets.items()}
    return "".join(
        symbol_for_set[frozenset(pairing[base] for base in base_sets[symbol])]
        for symbol in reversed(value.upper())
    )


def _deterministic_corpus(kind: str) -> list[str | None]:
    """Return all words through length three and seeded longer mixed-case rows."""
    alphabet = DNA_ALPHABET if kind == "dna" else RNA_ALPHABET
    values: list[str | None] = [
        "".join(symbols)
        for length in range(4)
        for symbols in product(alphabet, repeat=length)
    ]
    rng = random.Random(20261003)  # noqa: S311 - reproducible scientific fixture
    for length in [0, 1, 2, 3, 4, 15, 16, 31, 32, 63, 64, 255, 256, 4096]:
        for _ in range(8):
            sequence = "".join(rng.choice(alphabet) for _ in range(length))
            values.append(
                "".join(
                    symbol.lower() if rng.randrange(2) else symbol
                    for symbol in sequence
                )
            )
    values[1:1] = [None, "", alphabet.lower(), None, alphabet.lower()]
    return values


def test_native_module_is_a_compiled_extension() -> None:
    """Reject a Python fallback masquerading as the native implementation."""
    native = importlib.import_module("biov._native")
    origin = native.__file__
    assert origin is not None
    assert any(origin.endswith(suffix) for suffix in EXTENSION_SUFFIXES), origin
    assert Path(origin).parent == Path(biov.__file__).parent
    assert callable(native.normalize_sequences)
    assert callable(native.reverse_complements)


def test_validation_exception_is_shared_and_value_error() -> None:
    """Expose one public validation exception across both Python surfaces."""
    from biov.seq import SequenceValidationError

    assert biov.SequenceValidationError is SequenceValidationError
    assert issubclass(biov.SequenceValidationError, ValueError)


@pytest.mark.parametrize(
    ("kind", "alphabet"),
    [("dna", DNA_ALPHABET), ("rna", RNA_ALPHABET), ("protein", PROTEIN_ALPHABET)],
)
def test_complete_alphabets_normalize_without_losing_rows(
    kind: str, alphabet: str
) -> None:
    """Retain order, duplicates, empty strings and explicit nulls."""
    values = [alphabet.lower(), None, "", alphabet, alphabet.lower(), None]
    before = values.copy()
    result = biov.normalize_sequences(values, kind=kind)

    assert result == [alphabet, None, "", alphabet, alphabet, None]
    assert isinstance(result, list)
    assert result is not values
    assert values == before
    result[0] = ""
    assert values == before


@pytest.mark.parametrize(("symbol", "complement"), _DNA_SYMBOL_COMPLEMENTS)
@pytest.mark.parametrize("kind", ["dna", "rna"])
def test_every_iupac_symbol_has_its_hand_checked_complement(
    symbol: str, complement: str, kind: str
) -> None:
    """Check every ambiguity code individually, including lowercase inputs."""
    if kind == "rna":
        symbol = symbol.replace("T", "U")
        complement = complement.replace("T", "U")
    assert biov.reverse_complements([symbol, symbol.lower()], kind=kind) == [
        complement,
        complement,
    ]


@pytest.mark.parametrize(
    ("kind", "sequence", "expected"),
    [
        ("dna", "ACGTRYSWKMBDHVN", "NBDHVKMWSRYACGT"),
        ("rna", "ACGURYSWKMBDHVN", "NBDHVKMWSRYACGU"),
        ("dna", "aCGTryn", "NRYACGT"),
        ("rna", "aCGUryn", "NRYACGU"),
        ("dna", "AGTC", "GACT"),
        ("rna", "AGUC", "GACU"),
        ("rna", "augcryswkmbdhvn", "NBDHVKMWSRYGCAU"),
    ],
)
def test_complete_hand_derived_reverse_complement_fixtures(
    kind: str, sequence: str, expected: str
) -> None:
    """Check complete outputs instead of prefixes or preview strings."""
    values = [sequence, "", None, sequence, None]
    before = values.copy()
    result = biov.reverse_complements(values, kind=kind)

    assert result == [expected, "", None, expected, None]
    assert isinstance(result, list)
    assert result is not values
    assert values == before
    result[0] = ""
    assert values == before


@pytest.mark.parametrize("kind", ["dna", "rna"])
def test_full_corpus_agrees_with_independent_set_oracle(kind: str) -> None:
    """Compare every result with a set-based derivation of IUPAC complement."""
    values = _deterministic_corpus(kind)
    expected = [None if value is None else _set_oracle(value, kind) for value in values]
    assert biov.reverse_complements(values, kind=kind) == expected


@pytest.mark.parametrize("kind", ["dna", "rna"])
def test_full_corpus_agrees_with_versioned_biopython(
    kind: str, record_property: Callable[[str, object], None]
) -> None:
    """Run the separately implemented, pinned scientific differential reference."""
    record_property("biopython_reference_version", Bio.__version__)
    assert Bio.__version__ == REFERENCE_BIOPYTHON_VERSION, (
        "The scientific reference changed: install Biopython "
        f"{REFERENCE_BIOPYTHON_VERSION} from uv.lock, or explicitly review and "
        "update the reference version and sequence-contract provenance."
    )
    values = _deterministic_corpus(kind)
    expected = [
        None
        if value is None
        else str(
            ReferenceSeq(value.upper()).reverse_complement()
            if kind == "dna"
            else ReferenceSeq(value.upper()).reverse_complement_rna()
        )
        for value in values
    ]
    assert biov.reverse_complements(values, kind=kind) == expected


@pytest.mark.parametrize("kind", ["dna", "rna"])
def test_involution_lengths_and_batch_partitioning(kind: str) -> None:
    """Check algebraic and batch-boundary properties on complete outputs."""
    values = _deterministic_corpus(kind)
    before = values.copy()
    normalized = biov.normalize_sequences(values, kind=kind)
    reversed_values = biov.reverse_complements(values, kind=kind)

    assert biov.reverse_complements(reversed_values, kind=kind) == normalized
    assert biov.normalize_sequences(normalized, kind=kind) == normalized
    assert [None if value is None else len(value) for value in reversed_values] == [
        None if value is None else len(value) for value in values
    ]
    split = 19
    for operation in OPERATIONS:
        function = getattr(biov, operation)
        assert function(values, kind=kind) == (
            function(values[:split], kind=kind) + function(values[split:], kind=kind)
        )
    assert values == before


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("kind", ["dna", "rna"])
@pytest.mark.parametrize("values", [[], [None], [None, None], [""], [None, "", None]])
def test_empty_and_null_batches_are_preserved(
    operation: str, kind: str, values: list[str | None]
) -> None:
    """Keep missing and present zero-length sequences distinct."""
    result = getattr(biov, operation)(values, kind=kind)
    assert result == values
    assert result is not values


@pytest.mark.parametrize("values", [[], [None], [""], ["ACD"], [None, "", None]])
def test_protein_reverse_complement_is_rejected_without_data(
    values: list[str | None],
) -> None:
    """Validate operation kind even when no nonempty sequence is present."""
    with pytest.raises(TypeError):
        biov.reverse_complements(values, kind="protein")


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("kind", ["", "DNA", "RNA", "Protein", " dna", "dna ", "other"])
@pytest.mark.parametrize("values", [[], [None], ["AC"]])
def test_unknown_kinds_reject_even_empty_batches(
    operation: str, kind: str, values: list[str | None]
) -> None:
    """Never infer an alphabet or quietly repair a kind name."""
    with pytest.raises(ValueError):
        getattr(biov, operation)(values, kind=kind)


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("kind", [None, 1, True, b"dna", ["dna"]])
def test_non_string_kinds_raise_type_error(operation: str, kind: object) -> None:
    """Keep kind type errors separate from unknown string values."""
    with pytest.raises(TypeError):
        getattr(biov, operation)([], kind=kind)


@pytest.mark.parametrize("operation", OPERATIONS)
def test_kind_is_required_and_keyword_only(operation: str) -> None:
    """Require the explicit public calling convention."""
    function = getattr(biov, operation)
    with pytest.raises(TypeError):
        function([])
    with pytest.raises(TypeError):
        function([], "dna")


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("values", [None, "ACGT", b"ACGT", ("ACGT",), {"ACGT": 1}])
def test_non_list_inputs_are_not_coerced(operation: str, values: object) -> None:
    """Do not accidentally treat a scalar string as a batch of bases."""
    with pytest.raises(TypeError):
        getattr(biov, operation)(values, kind="dna")


@pytest.mark.parametrize("operation", OPERATIONS)
def test_generator_inputs_are_rejected(operation: str) -> None:
    """Do not silently broaden the chosen list representation to iterators."""
    values = (value for value in ["ACGT", None])
    with pytest.raises(TypeError):
        getattr(biov, operation)(values, kind="dna")


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize(
    "invalid", [42, 0.5, True, b"AC", ["AC"], {"sequence": "AC"}, ReferenceSeq("AC")]
)
def test_invalid_element_types_are_not_stringified(
    operation: str, invalid: object
) -> None:
    """Reject a bad element after valid rows without mutating the input batch."""
    values = ["ac", None, invalid, "gt"]
    before = values.copy()
    with pytest.raises(TypeError):
        getattr(biov, operation)(values, kind="dna")
    assert all(
        actual is original for actual, original in zip(values, before, strict=True)
    )


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("invalid", [float("nan"), pd.NA, pd.NaT])
def test_only_none_is_a_null_marker(operation: str, invalid: object) -> None:
    """Prevent pandas or floating-point missing semantics leaking into lists."""
    with pytest.raises(TypeError):
        getattr(biov, operation)([invalid], kind="dna")


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize(
    ("kind", "invalid"),
    [
        ("dna", "U"),
        ("dna", "u"),
        ("rna", "T"),
        ("rna", "t"),
        ("dna", "X"),
        ("rna", "x"),
    ],
)
def test_wrong_nucleotide_alphabet_is_not_transcribed(
    operation: str, kind: str, invalid: str
) -> None:
    """Validate declared DNA/RNA alphabets before sequence computation."""
    with pytest.raises(biov.SequenceValidationError):
        getattr(biov, operation)(["ac", invalid, None], kind=kind)


@pytest.mark.parametrize("operation", OPERATIONS)
@pytest.mark.parametrize("kind", ["dna", "rna"])
@pytest.mark.parametrize(
    "invalid",
    [
        " ",
        "\t",
        "\n",
        "\r",
        "-",
        ".",
        "0",
        "?",
        "*",
        "\x00",
        "é",
        "Ａ",
        "ß",
        "ſ",
        "ı",
        "\u00a0",
        "\U0001f9ec",
    ],
)
def test_invalid_symbols_reject_whole_batch_without_mutation(
    operation: str, kind: str, invalid: str
) -> None:
    """Reject Unicode, whitespace, gaps and punctuation without normalization loss."""
    values = ["ac", None, f"A{invalid}C", ""]
    before = values.copy()
    with pytest.raises(biov.SequenceValidationError):
        getattr(biov, operation)(values, kind=kind)
    assert values == before


@pytest.mark.parametrize("invalid", [" ", "-", ".", "3", "?", "ß", "ſ", "ı", "é"])
def test_protein_validation_is_ascii_only(invalid: str) -> None:
    """Preserve extended protein symbols without accepting Unicode substitutes."""
    with pytest.raises(biov.SequenceValidationError):
        biov.normalize_sequences([f"AC{invalid}D"], kind="protein")


def test_native_operations_do_not_call_biopython_reverse_complement(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Keep the migrated computation out of the old Python sequence backend."""

    def forbidden_reference_call(*args: object, **kwargs: object) -> None:
        pytest.fail("Native sequence computation called the Biopython reference")

    monkeypatch.setattr(ReferenceSeq, "reverse_complement", forbidden_reference_call)
    monkeypatch.setattr(
        ReferenceSeq, "reverse_complement_rna", forbidden_reference_call
    )
    assert biov.normalize_sequences(["aCgTryn", None, ""], kind="dna") == [
        "ACGTRYN",
        None,
        "",
    ]
    assert biov.reverse_complements(["aCgTryn", None, ""], kind="dna") == [
        "NRYACGT",
        None,
        "",
    ]
    assert biov.reverse_complements(["aCgUryn", None, ""], kind="rna") == [
        "NRYACGU",
        None,
        "",
    ]


@pytest.mark.parametrize(
    ("operation", "kind", "alphabet"),
    [
        ("normalize_sequences", "dna", DNA_ALPHABET),
        ("normalize_sequences", "rna", RNA_ALPHABET),
        ("normalize_sequences", "protein", PROTEIN_ALPHABET),
        ("reverse_complements", "dna", DNA_ALPHABET),
        ("reverse_complements", "rna", RNA_ALPHABET),
    ],
)
def test_ascii_acceptance_is_exact(operation: str, kind: str, alphabet: str) -> None:
    """Check every ASCII code point against the independently declared alphabet."""
    function = getattr(biov, operation)
    accepted = set(alphabet + alphabet.lower())
    for code_point in range(128):
        symbol = chr(code_point)
        if symbol in accepted:
            expected = symbol.upper()
            if operation == "reverse_complements":
                expected = _set_oracle(symbol, kind)
            assert function([symbol], kind=kind) == [expected], repr(symbol)
        else:
            with pytest.raises(biov.SequenceValidationError):
                function([symbol], kind=kind)


@pytest.mark.parametrize(
    ("operation", "kind"),
    [
        ("normalize_sequences", "dna"),
        ("normalize_sequences", "rna"),
        ("normalize_sequences", "protein"),
        ("reverse_complements", "dna"),
        ("reverse_complements", "rna"),
    ],
)
@pytest.mark.parametrize("code_points", [(0xD800,), (0xDFFF,), (0xD800, 0xDFFF)])
def test_surrogate_strings_raise_sequence_validation_error(
    operation: str, kind: str, code_points: tuple[int, ...]
) -> None:
    """Map non-UTF-8 Python strings to the public invalid-sequence exception."""
    invalid = "".join(chr(code_point) for code_point in code_points)
    values = ["ac", None, f"A{invalid}C", ""]
    before = values.copy()
    with pytest.raises(biov.SequenceValidationError):
        getattr(biov, operation)(values, kind=kind)
    assert values == before
