[package]
name = "biov-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]
test = false
doctest = false

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
biov-core.workspace = true
pyo3.workspace = true
